### ISSUE TITLE
Issues in configuring the plugin

### ISSUE THREAD

**Issue by dibegittest** [jenkinsci/salesforce-migration-assistant-plugin#14]
Hello,

We found this plugin very interesting and we're testing it to understand if it can bring benefit to our existing continuous integration system. Unfortunately we're running into the following issue, could you please advice us on how to proceed?

We run Jenkins v1.651.3 with Salesforce Migration Assistant Plugin v2.2.2. We have a job that is triggered by a pull request. Whatever we try we always get a NullPointerException.

GitHub pull request #5 of commit 541a5c7d2bca225e86425ba114219ed500197ded, has merge conflicts.
Setting status of 541a5c7d2bca225e86425ba114219ed500197ded to PENDING with url http://10.41.49.50:8080/job/SALESFORCE_MIGRATION_PLUGIN_TEST_RV/17/ and message: 'Build started sha1 is original commit.'
Building in workspace /var/lib/jenkins/jobs/SALESFORCE_MIGRATION_PLUGIN_TEST_RV/workspace
java.lang.NullPointerException
    at org.eclipse.jgit.internal.storage.file.UnpackedObjectCache$Table.index(UnpackedObjectCache.java:146)
    at org.eclipse.jgit.internal.storage.file.UnpackedObjectCache$Table.contains(UnpackedObjectCache.java:109)
    at org.eclipse.jgit.internal.storage.file.UnpackedObjectCache.isUnpacked(UnpackedObjectCache.java:64)
    at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:373)
    at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:145)
    at org.eclipse.jgit.treewalk.CanonicalTreeParser.reset(CanonicalTreeParser.java:202)
    at org.jenkinsci.plugins.sma.SMAGit.getTree(SMAGit.java:345)
    at org.jenkinsci.plugins.sma.SMAGit.getDiffs(SMAGit.java:328)
    at org.jenkinsci.plugins.sma.SMAGit.<init>(SMAGit.java:74)
    at org.jenkinsci.plugins.sma.SMARunner.<init>(SMARunner.java:74)
    at org.jenkinsci.plugins.sma.SMABuilder.perform(SMABuilder.java:65)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
    at hudson.model.Build$BuildExecution.build(Build.java:205)
    at hudson.model.Build$BuildExecution.doRun(Build.java:162)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
    at hudson.model.Run.execute(Run.java:1738)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)

Build step 'Salesforce Migration Assistant' marked build as failure
Setting status of 541a5c7d2bca225e86425ba114219ed500197ded to FAILURE with url http://10.41.49.50:8080/job/SALESFORCE_MIGRATION_PLUGIN_TEST_RV/17/ and message: 'Build finished. '
Finished: FAILURE

**Comment by karthikeyan68** [comment]
i too had similar error. while trying to setup the plugin and build it for first time

**Comment by Coogie7** [comment]
I can confirm I am getting a similar error as well. This was using a metadata type that is already supported (Apex Class), and replicating a test that worked the last time I tested it, about a month ago.

Here is error output:

[Salesforce-Test-Migration] $ /bin/sh -xe /tmp/hudson7721821741614560313.sh
+ echo 'Before Salesforce Migration Assistant'
Before Salesforce Migration Assistant
java.lang.NullPointerException
	at org.jenkinsci.plugins.sma.SMAMetadataTypes.createMetadataObject(SMAMetadataTypes.java:113)
	at org.jenkinsci.plugins.sma.SMARunner.buildMetadataList(SMARunner.java:227)
	at org.jenkinsci.plugins.sma.SMARunner.getPackageMembers(SMARunner.java:115)
	at org.jenkinsci.plugins.sma.SMABuilder.perform(SMABuilder.java:68)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)

Build step 'Salesforce Migration Assistant' marked build as failure
Finished: FAILURE

@aesanch2,
Any ideas what could be wrong? I'm still using the plugin you asked me to test earlier for issue #11 since an update hasn't been released yet to the [Jenkins plugin wiki](https://wiki.jenkins-ci.org/display/JENKINS/Salesforce+Migration+Assistant+Plugin). This could be a seperate issue than what @dibegittest posted, but I am guessing that isn't the case.

**Comment by aesanch2** [comment]
@dibegittest did you try running the plugin without a Merge Conflict?

I saw this in your provided output: 
```
GitHub pull request #5 of commit 541a5c7d2bca225e86425ba114219ed500197ded, has merge conflicts.
Setting status of 541a5c7d2bca225e86425ba114219ed500197ded to PENDING with url 
```

**Comment by codiyapa** [comment]
Hi,

I checked in new component in my GIT. but it is giving me this response:
05:56:01 [SMA] Deploying the following metadata:
05:56:01 
05:56:33 [SMA] Code Coverage Results
05:56:33 
05:56:33 Total code coverage for this deployment -- 0%
05:56:33 
05:56:33 [SMA] Deployment Succeeded
05:56:33 Finished: SUCCESS

None of the components are getting picked up. Can you please help?

**Comment by AshwiniChowdavarapu** [comment]
Hi, I am facing the same issue , Could you please share the resolution to this issue:
07:30:08 java.lang.NullPointerException
07:30:08 	at org.jenkinsci.plugins.sma.SMARunner.<init>(SMARunner.java:71)
07:30:08 	at org.jenkinsci.plugins.sma.SMABuilder.perform(SMABuilder.java:65)
07:30:08 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
07:30:08 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
07:30:08 	at hudson.model.Build$BuildExecution.build(Build.java:205)
07:30:08 	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
07:30:08 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
07:30:08 	at hudson.model.Run.execute(Run.java:1728)
07:30:08 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
07:30:08 	at hudson.model.ResourceController.execute(ResourceController.java:98)
07:30:08 	at hudson.model.Executor.run(Executor.java:404)
07:30:08 
07:30:08 Build step 'Salesforce Migration Assistant' marked build as failure

**Comment by neetiks** [comment]
Solution is in the file posted in this link.
Updated plugin-
https://github.com/jenkinsci/salesforce-migration-assistant-plugin/issues/11

**Comment by Raushansingh184** [comment]
I am also facing the Same Error, it is saying the build is completed but none of the components are getting deployed. I checked the #11 Solution as well. Even that is not helpful. I am in urgent need of this. 
Thanks in advance
