### ISSUE TITLE
New Releases?

### ISSUE THREAD

**Issue by hlopetz** [jenkinsci/salesforce-migration-assistant-plugin#19]
hi there,

do you have any plans to publish new releases?

as i can see, there is no dependency from ghprb-plugin on after version 2.2.2 i am experiencing [a problem](https://github.com/jenkinsci/ghprb-plugin/issues/433) with.

at the moment i am at Jenkins ver. 2.32.3. and the most recent version of SMA available there is 2.2.2.

as i can see, here are versions 2.2.3 and 3.0 in this repo. but i do not see binaries for them.

new stable releases either via standard Jenkins plugin update or as binaries would be appreciated.

thanks!

**Comment by hlopetz** [comment]
confirmed: release 3.0 built from sources solves the NullPointerException issue. thanks to @ronvelzeboer's fix.

**Comment by aesanch2** [comment]
@hlopetz I'll look into this. I do remember there being issues with binary releases a few releases ago.

**Comment by Sushmavn** [comment]
Hi , It will be of great help if you can let me know how to fix this issue. I am having the same issue. 

Thanks.

**Comment by luhugu** [comment]
@hlopetz I have same issue on cent os 7, do you know when new version 3.0 published?
java.lang.NullPointerException
	at org.jenkinsci.plugins.sma.SMARunner.<init>(SMARunner.java:71)
	at org.jenkinsci.plugins.sma.SMABuilder.perform(SMABuilder.java:65)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)

Build step 'Salesforce Migration Assistant' marked build as failure

**Comment by hlopetz** [comment]
guys, feel free to download the v 3.0 build from here:
https://drive.google.com/file/d/0Bzna52iZICaHZnJUUXJUOEhMeW8/view?usp=sharing

or follow the regular Jenkins CI guide on how to build a plugin from sources on you own, as i did:
https://wiki.jenkins-ci.org/display/JENKINS/Plugin+tutorial
(it does not require any IDE, but command-line util like `mvn`)

**Comment by sanjaykharwar** [comment]
@hlopetz link for v3.0 build worked for me. NullPointerException issue fixed after installing v3.0 and working properly.

**Comment by AshwiniChowdavarapu** [comment]
Hi @hlopetz / Sanjay ! Where do I have to install this v3.0

**Comment by hlopetz** [comment]
jenkins has ability to upload and install a plugin as a file from your
device. just check manuals on their website.

**Comment by hlopetz** [comment]
updated link: https://drive.google.com/file/d/0Bzna52iZICaHZnJUUXJUOEhMeW8/view?usp=sharing&resourcekey=0-SRD39B2XURpnAJIsUOqiwQ
