### ISSUE TITLE
Prevent Null Pointer Errors when proxy configuration isn't set

### ISSUE THREAD

**Issue by aesanch2** [jenkinsci/salesforce-migration-assistant-plugin#2]
```
java.lang.NullPointerException
	at org.jenkinsci.plugins.sma.SMAConnection.<init>(SMAConnection.java:71)
	at org.jenkinsci.plugins.sma.SMABuilder.perform(SMABuilder.java:92)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
```

**Comment by fracarma** [comment]
I've got this issue on Openshift instance of Jenkins. I cannot set the proxy due to _reverse proxy_ I think.

**Comment by jjulicher** [comment]
I seem to have this issue too on our AWS EC2 instance. 

Any ideas?

**Comment by aesanch2** [comment]
@jjulicher Generally speaking, this could be something to do with your Jenkins host's ability to connect to Salesforce.

You could troubleshoot this by seeing if your Jenkins instance can deploy metadata to Salesforce using the Force.com Migration Tool. I think any proxy issues encountered with the ANT tool would be the same issues that this plugin would face, since they're both using the Metadata API.

@fracarma I haven't had to work around a reverse proxy as of yet, but I'll see if I can replicate it.

**Comment by jjulicher** [comment]
Actually @aesanch2 I didn't read the trace properly.  I'm not experiencing this issue.  Sorry.

**Comment by tellanad** [comment]
java.lang.NullPointerException
	at org.jenkinsci.plugins.sma.SMARunner.<init>(SMARunner.java:71)
	at org.jenkinsci.plugins.sma.SMABuilder.perform(SMABuilder.java:65)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1727)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

Build step 'Salesforce Migration Assistant' marked build as failure
Finished: FAILURE

 Any idea ?

**Comment by rajkiran7117** [comment]
I`m Still facing the same issue ? Any solution on it ?
