### ISSUE TITLE
Receiving unknown failure

### ISSUE THREAD

**Issue by sfuser16** [jenkinsci/salesforce-migration-assistant-plugin#22]
I'm receiving a failure without much info in the logs. Pasting logs for your reference.
I feel that the configuration I've done is incorrect. I performed a step-by-step config from the documentation though.
Was hoping if you could let me know what could be the root cause of this issue.

 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/sfuser16/TriggerFramework.git # timeout=10
Fetching upstream changes from https://github.com/sfuser16/TriggerFramework.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials Personal Git Repo
 > git fetch --tags --progress https://github.com/sfuser16/TriggerFramework.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 04bdefcdbaebc953d6e7ce42277ee442ff4110a3 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 04bdefcdbaebc953d6e7ce42277ee442ff4110a3
 > git rev-list 04bdefcdbaebc953d6e7ce42277ee442ff4110a3 # timeout=10
java.lang.NullPointerException
	at org.jenkinsci.plugins.sma.SMARunner.<init>(SMARunner.java:71)
	at org.jenkinsci.plugins.sma.SMABuilder.perform(SMABuilder.java:65)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1735)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)

Build step 'Salesforce Migration Assistant' marked build as failure
Finished: FAILURE

**Comment by raqueldeniz** [comment]
This is affecting us as well. Anyone looking into this? Prob its because its the first time that we are using this , we are trying to configure our jenkins jobs for the first time and maybe we are missing something. Would be good to have someone to help us to make it working.
Regards,
Raquel Deniz

**Comment by sanjaykharwar** [comment]
This link worked for me....
https://github.com/jenkinsci/salesforce-migration-assistant-plugin/issues/19
