### ISSUE TITLE
Getting null pointer exception while consuming Salesforce Migration assistant plugin in Jenkins

### ISSUE THREAD

**Issue by Ved-Prakash-Coforge** [jenkinsci/salesforce-migration-assistant-plugin#31]
### Version report

Jenkins and plugins versions report:

```
Salesforce Migration assistant version: v2.2.2
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Windows operating system
```

### Reproduction steps

1. Created freestyle project and added git repo.
![image](https://user-images.githubusercontent.com/91194227/137301874-0b9b0f6e-7a04-46f5-8e16-d36e5b6d8069.png)
![image](https://user-images.githubusercontent.com/91194227/137301915-9b210b7a-9fa9-4fc9-84e7-4659cb01ec48.png)

2.  Given org. details to setup salesforce migration assistant
![image](https://user-images.githubusercontent.com/91194227/137302062-37cc109c-ef2d-4b4c-a4b1-bb8de63d5a0e.png)

3. while running the project in Jenkins getting below error
[Checks API] No suitable checks publisher found.
java.lang.NullPointerException
	at org.jenkinsci.plugins.sma.SMARunner.<init>(SMARunner.java:71)
	at org.jenkinsci.plugins.sma.SMABuilder.perform(SMABuilder.java:65)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:806)
	at hudson.model.Build$BuildExecution.build(Build.java:198)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:514)
	at hudson.model.Run.execute(Run.java:1888)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:99)
	at hudson.model.Executor.run(Executor.java:431)

Build step 'Salesforce Migration Assistant' marked build as failure
[Checks API] No suitable checks publisher found.
Finished: FAILURE
![image](https://user-images.githubusercontent.com/91194227/137302382-4b1dbfb4-fad3-4c7e-b1bb-58974cd545f8.png)

### Results

Expected result: it's should connected to the Salesforce Org. to deploy delta changes in the source using Jenkins

Actual result: Null pointer exception is coming as mentioned under point 3

**Comment by hlopetz** [comment]
check #19

**Comment by Ved-Prakash-Coforge** [comment]
> check #19

Thanks hlopetz for the quick response,

I used the latest release 3.0 and now Null pointer exception is not coming but when I am running the job then nothing is deploying in the org. check below screens for reference.

### **Screen 1:** Empty deployment is happening
![image](https://user-images.githubusercontent.com/91194227/137319463-b71b7ca3-0a5d-4f3b-b2c6-27648869105e.png)

### **Screen 2:** Console Output
![image](https://user-images.githubusercontent.com/91194227/137319885-51a1ba23-9d6d-40f8-9ab9-9789fb334c13.png)

**Comment by hlopetz** [comment]
tbh, i personally got rid of the plugin usage and set Jenkins up with `sfdx` command. so i cannpt help you further, sorry.

the shell script i use is

```
TIMEOUT=120

/usr/local/bin/sfdx force:org:list --all --verbose
export SFDX_IMPROVED_CODE_COVERAGE='true'
/usr/local/bin/sfdx force:apex:test:run \
	--targetusername Full \
	--resultformat junit \
	--outputdir . \
	--codecoverage \
	--testlevel RunLocalTests \
	--wait $TIMEOUT \
	--verbose 2> error.log > run.log || exit 0
echo echo error log:
cat error.log
```

that setup does not deploy a specific revision, but runs a build on a sandbox i need to check every night to control if admins made a change which broke anything. i have the same for production instance.

**Comment by hlopetz** [comment]
but you can adapt the script above to deploy a specific package/revision to a scratch org and run the tests you like.
